create table if not exists item (
  id int primary key generated by default as identity, 
  publish_date date not null,
  archived bool not null
);

create table if not exists game (
  id int primary key generated by default as identity,
  multiplayer bool not null,
  last_played_at date not null,
  item_id int not null,
  constraint fk_game_item foreign key(item_id) references item(id) on delete cascade
);

create table if not exists author (
  id int primary key generated by default as identity,
  first_name text not null,
  last_name text not null
);

-- create table if not exists music_album (
--   id int primary key generated by default as identity,
--   on_spotify bool not null,
--   last_played_at date not null,
--   item_id int not null,
--   constraint fk_game_item foreign key(item_id) references item(id) on delete cascade
-- );

-- create table if not exists genre (
--   id int primary key generated by default as identity,
--   name text not null,
-- );
